// mclib
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Snapshot pose-correction tests. Everything here is pure geometry: the solver
// takes ranges as numbers, so no distance sensor and no PROS header is
// involved. Readings are generated by ray-casting from a known true pose, then
// handed to the solver with a deliberately wrong guess.

#include "mclib/snapshot/solver.hpp"
#include "test_assert.hpp"

#include <cmath>
#include <cstdio>
#include <vector>

using snapshot::SensorGeometry;
using snapshot::SensorMeasurement;
using snapshot::SnapshotConfig;
using snapshot::SnapshotReject;
using snapshot::SnapshotResult;
using snapshot::Vec2;

namespace {

SnapshotConfig baseConfig() {
  SnapshotConfig cfg{};
  cfg.field_mask = snapshot::MAP_PERIMETER;
  cfg.min_sensors = 2u;
  cfg.max_iterations = 8u;
  cfg.max_chi2_per_sensor = 9.0f;
  cfg.max_correction_in = 12.0f;
  cfg.max_residual_in = 24.0f;
  return cfg;
}

SensorGeometry mount(float right_in, float fwd_in, float rel_deg) {
  SensorGeometry g{};
  g.x_right_in = right_in;
  g.y_fwd_in = fwd_in;
  g.rel_deg = rel_deg;
  g.field_mask = snapshot::MAP_PERIMETER;
  g.max_range_in = 144.0f;
  return g;
}

/// Synthesise the range a sensor would report from a known true pose.
float trueRange(const SensorGeometry& g, float x, float y, float heading_deg,
                const SnapshotConfig& cfg) {
  const snapshot::RayPrediction p =
      snapshot::predict_range(g, x, y, heading_deg, cfg.field_mask);
  return p.valid ? p.expected_in : -1.0f;
}

float dist(float ax, float ay, float bx, float by) {
  return std::sqrt((ax - bx) * (ax - bx) + (ay - by) * (ay - by));
}

// -------------------------------------------------------------------------
// 1. The frame check. A sensor 7 in to the robot's right must leave from a
//    different field position for every heading. The old code added
//    x_right_in straight onto field X and got the same answer every time.
// -------------------------------------------------------------------------
void testSensorOriginRotatesWithHeading() {
  const SensorGeometry right = mount(7.0f, 0.0f, 90.0f);

  // Heading 0: robot faces +Y, its right is +X.
  const Vec2 o0 = snapshot::sensor_origin_field(right, 72.0f, 72.0f, 0.0f);
  CHECK_NEAR(o0.x, 79.0, 1e-4);
  CHECK_NEAR(o0.y, 72.0, 1e-4);

  // Heading 90: robot faces +X, its right is -Y. This is the assertion the
  // pre-fix code failed - it also returned (79, 72) here.
  const Vec2 o90 = snapshot::sensor_origin_field(right, 72.0f, 72.0f, 90.0f);
  CHECK_NEAR(o90.x, 72.0, 1e-4);
  CHECK_NEAR(o90.y, 65.0, 1e-4);

  // Heading 180: right is -X.
  const Vec2 o180 = snapshot::sensor_origin_field(right, 72.0f, 72.0f, 180.0f);
  CHECK_NEAR(o180.x, 65.0, 1e-4);
  CHECK_NEAR(o180.y, 72.0, 1e-4);

  // A forward-mounted sensor moves along the heading vector.
  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  const Vec2 f90 = snapshot::sensor_origin_field(front, 72.0f, 72.0f, 90.0f);
  CHECK_NEAR(f90.x, 79.0, 1e-4);
  CHECK_NEAR(f90.y, 72.0, 1e-4);

  // Ray directions follow the compass convention: (sin, cos).
  const Vec2 d0 = snapshot::sensor_direction_field(right, 0.0f);
  CHECK_NEAR(d0.x, 1.0, 1e-5);
  CHECK_NEAR(d0.y, 0.0, 1e-5);
  const Vec2 d90 = snapshot::sensor_direction_field(right, 90.0f);
  CHECK_NEAR(d90.x, 0.0, 1e-5);
  CHECK_NEAR(d90.y, -1.0, 1e-5);
}

// -------------------------------------------------------------------------
// 2. Ray-casting: nearest hit, and the field mask is honoured.
// -------------------------------------------------------------------------
void testRaycastNearestHitAndMask() {
  // From (72, 72) looking -X: the long goal wall at x = 18 is nearer than the
  // perimeter at x = 0.
  const Vec2 origin{72.0f, 72.0f};
  const Vec2 dir{-1.0f, 0.0f};

  const std::vector<snapshot::RayHit> all = snapshot::raycast_all(
      origin, dir, 144.0f, snapshot::MAP_PERIMETER | snapshot::MAP_LONG_GOALS);
  CHECK(all.size() >= 2u);
  CHECK_NEAR(all.front().t_in, 54.0, 1e-3);  // 72 - 18
  // Sorted by distance.
  for (std::size_t i = 1u; i < all.size(); ++i) {
    CHECK(all[i - 1u].t_in <= all[i].t_in);
  }

  // Mask out the goal and the perimeter is the nearest hit.
  const std::vector<snapshot::RayHit> walls_only =
      snapshot::raycast_all(origin, dir, 144.0f, snapshot::MAP_PERIMETER);
  CHECK_EQ(walls_only.size(), 1u);
  CHECK_NEAR(walls_only.front().t_in, 72.0, 1e-3);

  // Range limit drops the hit entirely.
  const std::vector<snapshot::RayHit> short_range =
      snapshot::raycast_all(origin, dir, 10.0f, snapshot::MAP_PERIMETER);
  CHECK(short_range.empty());
}

// -------------------------------------------------------------------------
// 3. The solve moves the estimate toward the truth, and converges onto it.
// -------------------------------------------------------------------------
void testSolveConvergesToTruth() {
  const SnapshotConfig cfg = baseConfig();
  const float heading = 30.0f;
  const float true_x = 30.0f;
  const float true_y = 40.0f;

  // Front sensor and a left-looking sensor: two non-parallel walls, so (x, y)
  // is fully observable.
  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  const SensorGeometry left = mount(-6.0f, 1.0f, -90.0f);

  std::vector<SensorMeasurement> readings;
  readings.push_back({front, trueRange(front, true_x, true_y, heading, cfg)});
  readings.push_back({left, trueRange(left, true_x, true_y, heading, cfg)});
  CHECK(readings[0].measured_in > 0.0f);
  CHECK(readings[1].measured_in > 0.0f);

  const float guess_x = true_x + 3.0f;
  const float guess_y = true_y - 2.5f;
  const float before = dist(guess_x, guess_y, true_x, true_y);

  const SnapshotResult r =
      snapshot::solve_snapshot(readings, cfg, guess_x, guess_y, heading);
  const float after = dist(r.x_in, r.y_in, true_x, true_y);

  std::printf("  converge: before %.4f in, after %.4f in, chi2 %.2e -> %.2e, %u iters\n",
              static_cast<double>(before), static_cast<double>(after),
              static_cast<double>(r.chi2_initial), static_cast<double>(r.chi2),
              r.iterations);

  CHECK(r.success);
  CHECK_EQ(static_cast<int>(r.reject), static_cast<int>(SnapshotReject::NONE));
  CHECK_EQ(r.used_samples, 2u);
  CHECK(after < before);
  CHECK_NEAR(after, 0.0, 0.05);
  CHECK_NEAR(r.x_in, true_x, 0.05);
  CHECK_NEAR(r.y_in, true_y, 0.05);
  CHECK(r.chi2 < 1e-2f);
}

// -------------------------------------------------------------------------
// 4. With noise on the readings the solve still shrinks the error a lot, and
//    the reported correction matches the distance actually moved.
// -------------------------------------------------------------------------
void testSolveWithNoisyReadings() {
  const SnapshotConfig cfg = baseConfig();
  const float heading = 0.0f;
  const float true_x = 100.0f;
  const float true_y = 24.0f;

  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  const SensorGeometry right = mount(7.0f, 0.0f, 90.0f);
  const SensorGeometry back = mount(0.0f, -7.0f, 180.0f);

  std::vector<SensorMeasurement> readings;
  readings.push_back({front, trueRange(front, true_x, true_y, heading, cfg) + 0.4f});
  readings.push_back({right, trueRange(right, true_x, true_y, heading, cfg) - 0.3f});
  readings.push_back({back, trueRange(back, true_x, true_y, heading, cfg) + 0.2f});

  const float guess_x = true_x - 4.0f;
  const float guess_y = true_y + 1.0f;
  const float before = dist(guess_x, guess_y, true_x, true_y);

  const SnapshotResult r =
      snapshot::solve_snapshot(readings, cfg, guess_x, guess_y, heading);
  const float after = dist(r.x_in, r.y_in, true_x, true_y);

  std::printf("  noisy: before %.4f in, after %.4f in, chi2 %.4f -> %.4f, moved %.4f in\n",
              static_cast<double>(before), static_cast<double>(after),
              static_cast<double>(r.chi2_initial), static_cast<double>(r.chi2),
              static_cast<double>(r.correction_in));

  CHECK(r.success);
  CHECK_EQ(r.used_samples, 3u);
  CHECK(after < before);
  CHECK(after < 0.5f);
  CHECK_NEAR(r.correction_in, dist(guess_x, guess_y, r.x_in, r.y_in), 1e-4);
}

// -------------------------------------------------------------------------
// 5. The gate. A reading no pose explains must not move the robot.
// -------------------------------------------------------------------------
void testGateRejectsInconsistentReadings() {
  const SnapshotConfig cfg = baseConfig();
  const float heading = 0.0f;
  const float true_x = 72.0f;
  const float true_y = 30.0f;

  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  const SensorGeometry right = mount(7.0f, 0.0f, 90.0f);
  const SensorGeometry left = mount(-7.0f, 0.0f, -90.0f);

  // Front and right are honest; the left sensor is looking at another robot
  // 20 in away, which no position on this map explains together with the
  // other two.
  std::vector<SensorMeasurement> readings;
  readings.push_back({front, trueRange(front, true_x, true_y, heading, cfg)});
  readings.push_back({right, trueRange(right, true_x, true_y, heading, cfg)});
  readings.push_back({left, trueRange(left, true_x, true_y, heading, cfg) - 20.0f});

  const SnapshotResult r =
      snapshot::solve_snapshot(readings, cfg, true_x, true_y, heading);

  std::printf("  gate: reject=%d chi2=%.3f correction=%.3f in\n",
              static_cast<int>(r.reject), static_cast<double>(r.chi2),
              static_cast<double>(r.correction_in));

  CHECK(!r.success);
  CHECK_EQ(static_cast<int>(r.reject), static_cast<int>(SnapshotReject::CHI2));
  // Pose untouched.
  CHECK_NEAR(r.x_in, true_x, 1e-6);
  CHECK_NEAR(r.y_in, true_y, 1e-6);
}

// -------------------------------------------------------------------------
// 6. A wildly wrong reading is dropped by the residual prefilter rather than
//    poisoning the fit, and the honest sensors still correct the pose.
// -------------------------------------------------------------------------
void testGrossOutlierIsDroppedNotFitted() {
  const SnapshotConfig cfg = baseConfig();
  const float heading = 0.0f;
  const float true_x = 72.0f;
  const float true_y = 30.0f;

  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  const SensorGeometry right = mount(7.0f, 0.0f, 90.0f);
  const SensorGeometry left = mount(-7.0f, 0.0f, -90.0f);

  std::vector<SensorMeasurement> readings;
  readings.push_back({front, trueRange(front, true_x, true_y, heading, cfg)});
  readings.push_back({right, trueRange(right, true_x, true_y, heading, cfg)});
  readings.push_back({left, 2.0f});  // 60+ in off: a robot right beside us.

  const float guess_x = true_x + 2.0f;
  const float guess_y = true_y + 2.0f;
  const float before = dist(guess_x, guess_y, true_x, true_y);
  const SnapshotResult r =
      snapshot::solve_snapshot(readings, cfg, guess_x, guess_y, heading);
  const float after = dist(r.x_in, r.y_in, true_x, true_y);

  std::printf("  outlier: kept %zu of 3, before %.4f in, after %.4f in\n",
              r.used_samples, static_cast<double>(before),
              static_cast<double>(after));

  CHECK_EQ(r.used_samples, 2u);
  CHECK(r.success);
  CHECK(after < before);
  CHECK_NEAR(after, 0.0, 0.05);
}

// -------------------------------------------------------------------------
// 7. A correction bigger than max_correction_in is refused outright.
// -------------------------------------------------------------------------
void testGateRejectsLargeCorrection() {
  SnapshotConfig cfg = baseConfig();
  cfg.max_correction_in = 2.0f;
  cfg.max_residual_in = 60.0f;  // let the readings past the prefilter

  const float heading = 0.0f;
  const float true_x = 60.0f;
  const float true_y = 60.0f;

  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  const SensorGeometry right = mount(7.0f, 0.0f, 90.0f);

  std::vector<SensorMeasurement> readings;
  readings.push_back({front, trueRange(front, true_x, true_y, heading, cfg)});
  readings.push_back({right, trueRange(right, true_x, true_y, heading, cfg)});

  // Guess is 20 in away. The fit is perfect at the truth, but moving there is
  // a bigger jump than we allow, so it is refused.
  const float guess_x = true_x + 12.0f;
  const float guess_y = true_y + 16.0f;
  const SnapshotResult r =
      snapshot::solve_snapshot(readings, cfg, guess_x, guess_y, heading);

  std::printf("  large correction: reject=%d wanted %.3f in (cap %.1f)\n",
              static_cast<int>(r.reject), static_cast<double>(r.correction_in),
              static_cast<double>(cfg.max_correction_in));

  CHECK(!r.success);
  CHECK_EQ(static_cast<int>(r.reject),
           static_cast<int>(SnapshotReject::CORRECTION_TOO_LARGE));
  CHECK_NEAR(r.x_in, guess_x, 1e-6);
  CHECK_NEAR(r.y_in, guess_y, 1e-6);
}

// -------------------------------------------------------------------------
// 8. Degenerate cases: no sensors, too few sensors, everything rejected.
// -------------------------------------------------------------------------
void testTooFewSensors() {
  const SnapshotConfig cfg = baseConfig();
  const float heading = 0.0f;

  // No sensors at all.
  const SnapshotResult empty =
      snapshot::solve_snapshot({}, cfg, 40.0f, 40.0f, heading);
  CHECK(!empty.success);
  CHECK_EQ(static_cast<int>(empty.reject),
           static_cast<int>(SnapshotReject::NO_SENSORS));
  CHECK_NEAR(empty.x_in, 40.0, 1e-6);
  CHECK_NEAR(empty.y_in, 40.0, 1e-6);

  // One sensor with min_sensors = 2: refused, pose untouched.
  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  std::vector<SensorMeasurement> one;
  one.push_back({front, trueRange(front, 40.0f, 40.0f, heading, cfg)});
  const SnapshotResult single =
      snapshot::solve_snapshot(one, cfg, 42.0f, 38.0f, heading);
  CHECK(!single.success);
  CHECK_EQ(static_cast<int>(single.reject),
           static_cast<int>(SnapshotReject::TOO_FEW_SENSORS));
  CHECK_EQ(single.used_samples, 1u);
  CHECK_NEAR(single.x_in, 42.0, 1e-6);
  CHECK_NEAR(single.y_in, 38.0, 1e-6);

  // Every reading fails the prefilter.
  std::vector<SensorMeasurement> junk;
  junk.push_back({front, 1.0f});
  junk.push_back({mount(7.0f, 0.0f, 90.0f), 1.0f});
  const SnapshotResult all_rejected =
      snapshot::solve_snapshot(junk, cfg, 72.0f, 72.0f, heading);
  CHECK(!all_rejected.success);
  CHECK_EQ(all_rejected.used_samples, 0u);
  CHECK_EQ(static_cast<int>(all_rejected.reject),
           static_cast<int>(SnapshotReject::TOO_FEW_SENSORS));
  CHECK_NEAR(all_rejected.x_in, 72.0, 1e-6);
  CHECK_NEAR(all_rejected.y_in, 72.0, 1e-6);

  // Non-positive readings never reach the solver.
  std::vector<SensorMeasurement> zeros;
  zeros.push_back({front, 0.0f});
  zeros.push_back({mount(7.0f, 0.0f, 90.0f), -5.0f});
  const SnapshotResult zeroed =
      snapshot::solve_snapshot(zeros, cfg, 72.0f, 72.0f, heading);
  CHECK(!zeroed.success);
  CHECK_EQ(zeroed.used_samples, 0u);
}

// -------------------------------------------------------------------------
// 9. Two parallel walls leave one axis unobservable. min_sensors is satisfied,
//    so the solve runs - and must not invent motion along the free axis.
// -------------------------------------------------------------------------
void testParallelWallsDoNotDriftFreeAxis() {
  const SnapshotConfig cfg = baseConfig();
  const float heading = 0.0f;
  const float true_x = 72.0f;
  const float true_y = 40.0f;

  // Front (+Y wall) and back (-Y wall): both pin down y, neither sees x.
  const SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  const SensorGeometry back = mount(0.0f, -7.0f, 180.0f);

  std::vector<SensorMeasurement> readings;
  readings.push_back({front, trueRange(front, true_x, true_y, heading, cfg)});
  readings.push_back({back, trueRange(back, true_x, true_y, heading, cfg)});

  const float guess_x = true_x + 5.0f;
  const float guess_y = true_y + 3.0f;
  const SnapshotResult r =
      snapshot::solve_snapshot(readings, cfg, guess_x, guess_y, heading);

  std::printf("  parallel: x %.4f -> %.4f (guess kept), y err %.4f -> %.4f\n",
              static_cast<double>(guess_x), static_cast<double>(r.x_in),
              static_cast<double>(guess_y - true_y),
              static_cast<double>(r.y_in - true_y));

  CHECK(r.success);
  // x is unobservable: the damped solve leaves it at the guess.
  CHECK_NEAR(r.x_in, guess_x, 1e-3);
  // y is observable and gets fixed.
  CHECK_NEAR(r.y_in, true_y, 0.05);
}

// -------------------------------------------------------------------------
// 10. The same true pose is recovered at several headings. A mirrored frame
//     passes at heading 0 and fails everywhere else, so sweep.
// -------------------------------------------------------------------------
void testConvergesAcrossHeadings() {
  const SnapshotConfig cfg = baseConfig();
  const float true_x = 50.0f;
  const float true_y = 95.0f;
  const float headings[] = {0.0f, 45.0f, 90.0f, 135.0f, 180.0f, -90.0f, -135.0f};

  // Three sensors, not two: at heading 45 a front/right pair happens to see
  // the +Y and -Y walls, which pins down y and leaves x free. That is a real
  // degeneracy of the geometry, not a solver bug - the back sensor is what
  // makes x observable there.
  const SensorGeometry front = mount(2.0f, 8.0f, 0.0f);
  const SensorGeometry right = mount(6.0f, -2.0f, 90.0f);
  const SensorGeometry back = mount(-1.0f, -8.0f, 180.0f);
  const SensorGeometry mounts[] = {front, right, back};

  float worst = 0.0f;
  for (const float heading : headings) {
    std::vector<SensorMeasurement> readings;
    bool usable = true;
    for (const SensorGeometry& g : mounts) {
      const float range = trueRange(g, true_x, true_y, heading, cfg);
      if (range <= 0.0f) {
        usable = false;
        break;
      }
      readings.push_back({g, range});
    }
    if (!usable) {
      continue;
    }
    const SnapshotResult r = snapshot::solve_snapshot(
        readings, cfg, true_x - 2.0f, true_y + 2.0f, heading);
    CHECK(r.success);
    const float err = dist(r.x_in, r.y_in, true_x, true_y);
    if (err > worst) {
      worst = err;
    }
    CHECK_NEAR(err, 0.0, 0.05);
  }
  std::printf("  heading sweep: worst residual error %.4f in over %zu headings\n",
              static_cast<double>(worst), sizeof(headings) / sizeof(headings[0]));
}

// -------------------------------------------------------------------------
// 11. A reading past the sensor's own ceiling is "saw nothing", not a range.
//     The V5 distance sensor reports 9999 mm (393 in) when nothing is in
//     range; letting that into the fit as a measurement biases every residual.
// -------------------------------------------------------------------------
void testReadingBeyondSensorRangeIsDropped() {
  const SnapshotConfig cfg = baseConfig();
  const float heading = 0.0f;
  const float true_x = 72.0f;
  const float true_y = 100.0f;

  SensorGeometry front = mount(0.0f, 7.0f, 0.0f);
  SensorGeometry right = mount(7.0f, 0.0f, 90.0f);
  SensorGeometry left = mount(-7.0f, 0.0f, -90.0f);
  front.max_range_in = 78.0f;
  right.max_range_in = 78.0f;
  left.max_range_in = 78.0f;

  std::vector<SensorMeasurement> readings;
  readings.push_back({front, trueRange(front, true_x, true_y, heading, cfg)});
  readings.push_back({right, trueRange(right, true_x, true_y, heading, cfg)});
  readings.push_back({left, 393.6f});  // 9999 mm: out of range, not a distance.

  const SnapshotResult r =
      snapshot::solve_snapshot(readings, cfg, true_x + 1.0f, true_y + 1.0f, heading);

  std::printf("  out-of-range: kept %zu of 3, success=%d\n", r.used_samples,
              static_cast<int>(r.success));

  CHECK_EQ(r.used_samples, 2u);
  CHECK(r.success);
  CHECK_NEAR(dist(r.x_in, r.y_in, true_x, true_y), 0.0, 0.05);

  // The prediction is truncated at the same ceiling too, so a wall the sensor
  // could not have measured is reported as no hit rather than as a range.
  // From (72, 30) the front sensor is 107 in from the wall at y = 144.
  const snapshot::RayPrediction far =
      snapshot::predict_range(front, 72.0f, 30.0f, heading, cfg.field_mask);
  CHECK(!far.valid);
  const snapshot::RayPrediction near_wall =
      snapshot::predict_range(front, true_x, true_y, heading, cfg.field_mask);
  CHECK(near_wall.valid);
  CHECK_NEAR(near_wall.expected_in, 37.0, 1e-3);
}

}  // namespace

int main() {
  testSensorOriginRotatesWithHeading();
  testRaycastNearestHitAndMask();
  testSolveConvergesToTruth();
  testSolveWithNoisyReadings();
  testGateRejectsInconsistentReadings();
  testGrossOutlierIsDroppedNotFitted();
  testGateRejectsLargeCorrection();
  testTooFewSensors();
  testParallelWallsDoNotDriftFreeAxis();
  testConvergesAcrossHeadings();
  testReadingBeyondSensorRangeIsDropped();
  return mclib::test::summary("snapshot");
}
