// mclib
#pragma once

#include "mclib/units/units.hpp"
#include "mclib/math.hpp"
#include "mclib/sync.hpp"
#include "mclib/time.hpp"
#include "mclib/utils.hpp"
#include "mclib/pid.hpp"
#include "mclib/auton/autonomous_routine.hpp"
#include "mclib/config.hpp"
#include "mclib/control.hpp"
#include "mclib/chassis/chassis.hpp"
#include "mclib/chassis/chassis_controller.hpp"
#include "mclib/command/includes.h"
#include "mclib/device/controller.hpp"
#include "mclib/device/distance.hpp"
#include "mclib/device/imu.hpp"
#include "mclib/device/inertial.hpp"
#include "mclib/device/line.hpp"
#include "mclib/device/motor.hpp"
#include "mclib/device/motor_group.hpp"
#include "mclib/device/pneumatic.hpp"
#include "mclib/device/rotation.hpp"
#include "mclib/device/types.hpp"
#include "mclib/mechanism/auto_trigger_mechanism.hpp"
#include "mclib/mechanism/conveyor_mechanism.hpp"
#include "mclib/mechanism/discrete_actuator_mechanism.hpp"
#include "mclib/mechanism/homing_mechanism.hpp"
#include "mclib/mechanism/mechanism.hpp"
#include "mclib/mechanism/mechanism_manager.hpp"
#include "mclib/mechanism/motor_state_mechanism.hpp"
#include "mclib/mechanism/motor_subsystem.hpp"
#include "mclib/mechanism/multi_position_mechanism.hpp"
#include "mclib/mechanism/pneumatic_subsystem.hpp"
#include "mclib/mechanism/position_mechanism.hpp"
#include "mclib/mechanism/preset_position_mechanism.hpp"
#include "mclib/mechanism/pto_mechanism.hpp"
#include "mclib/mechanism/toggle_group_mechanism.hpp"
#include "mclib/mechanism/toggle_mechanism.hpp"
#include "mclib/mechanism/velocity_mechanism.hpp"
#include "mclib/snapshot/snapshot_config.hpp"

#ifndef MCLIB_NO_ALIAS
namespace ml = mclib;
#endif
